### PR TITLE
#13 persist authentication

### PR DESCRIPTION
**Pull request by dj-256**
* Persist authentication
  * Install @capacitor/preferences for native device preferences access
  * New preferences.js file with `setPreference` and `getPreference` functions
  * New hooks.js file with `useUser` and `useUserInfo` hooks to get data from preferences
  * Add redirection to "/app" for "/onboarding" if the user is logged in
  * Remove `userInfo` global state
  * Remove `AppContext`
  * Rename `checkToken` into `checkTokenAndFetchUser` in auth.js
  * Remove platform, token and url from function arguments and get them directly from Capacitor
  * Use React query mutation to log user in, in CheckQRCodeScreen.jsx
  * Add constants for preferences
  * Use `history.replace` in LoginOkScreen.jsx
  * Activate `checkJs` in tsconfig.json and fix typing
* New custom hooks
  * Put QueryClientProvider in main.jsx
  * New constant `QUERY_KEYS`
  * New `useSearchCandidates` and `useFetchSources` hooks
* Skip onboarding in dev mode
  * New config.js file
  * New env.d.ts file to fix tslint for vite env
  * New `useSkipOnboarding` hook to automatically skip onboarding if the configuration allows it
  * Use `useSkipOnboarding` hook in App.jsx

### CODE REVIEW

**Review by Theodlz — COMMENTED** [review]
Code looks good by itself but I'm having some issues:
- upon login with QRCode I can't see the source list and looking at the logs I see the error "sources.map" is not a function, so likely sources is not a list and couldn't be fetched.
- If I cancel login with the QRCode the app still proceeds to log me in or at least says that it logged it successfully when clearly it didn't.
- On the candidates page, after selecting a few options and trying to scan (unsuccessfully caus can't login), then clicking on the other menus in the app bar at the bottom does not work, it's stuck on the scanning page.

**Comment by Theodlz** [comment]
I wonder if a welcome screen telling you what instance you are auto-connecting to would be useful. If not there, we probably need an about/setting tab where you can see that kind of info. Otherwise can't tell for sure which instance I am connected to.

**Comment by dj-256** [comment]
> Looks like `npm i` fixed it, my bad!
> 
> Makes me think about whether or not when using dev commands, we want to have a dependency check + auto install run in the future, just like we do with SkyPortal. It's very convenient

I don't understand what this means

**Comment by Theodlz** [comment]
> > Looks like `npm i` fixed it, my bad!
> > Makes me think about whether or not when using dev commands, we want to have a dependency check + auto install run in the future, just like we do with SkyPortal. It's very convenient
> 
> I don't understand what this means

It's a dev quality of life comment in general. For example, when I run SkyPortal locally while developing, I don't need to worry about whether or not my dependencies are up-to-date with the PR. When I start the app, it checks the dependencies and automagically updates or installs what is missing. It's a nice way to avoid that kind of issues I ran into when switching between branches, and therefore makes development a little easier. It's a "nice to have" however; and definitely not a "must-have".

**Comment by dj-256** [comment]
> > > Looks like `npm i` fixed it, my bad!
> > > Makes me think about whether or not when using dev commands, we want to have a dependency check + auto install run in the future, just like we do with SkyPortal. It's very convenient
> > 
> > 
> > I don't understand what this means
> 
> It's a dev quality of life comment in general. For example, when I run SkyPortal locally while developing, I don't need to worry about whether or not my dependencies are up-to-date with the PR. When I start the app, it checks the dependencies and automagically updates or installs what is missing. It's a nice way to avoid that kind of issues I ran into when switching between branches, and therefore makes development a little easier. It's a "nice to have", however; and definitely not a "must-have".

Alright I see. It's very standard though, to have to npm i when dependencies change. It might be weird for web devs to find it handled another way. We could just add a custom script or have a pre-script for people who don't want to have to npm i when a new dependency is added.

**Comment by Theodlz** [comment]
> > > > Looks like `npm i` fixed it, my bad!
> > > > Makes me think about whether or not when using dev commands, we want to have a dependency check + auto install run in the future, just like we do with SkyPortal. It's very convenient
> > > 
> > > 
> > > I don't understand what this means
> > 
> > 
> > It's a dev quality of life comment in general. For example, when I run SkyPortal locally while developing, I don't need to worry about whether or not my dependencies are up-to-date with the PR. When I start the app, it checks the dependencies and automagically updates or installs what is missing. It's a nice way to avoid that kind of issues I ran into when switching between branches, and therefore makes development a little easier. It's a "nice to have", however; and definitely not a "must-have".
> 
> Alright I see. It's very standard though, to have to npm i when dependencies change. It might be weird for web devs to find it handled another way. We could just add a custom script or have a pre-script for people who don't want to have to npm i when a new dependency is added.

Both are fine, could be as simple as just adding the `npm i` to dev commands like `"dev:external": "ionic cap run android -l --external",`. When switching between PRs it gets old pretty quickly to have to run it manually everytime, so might as well have it in there, though I get your point about whatever is the standard. Feel free to just not do it, again it's everything but a high priority item

**Pull request merged**
