### PR TITLE
29 main scanning page

### PR DESCRIPTION
**Pull request by dj-256**
This adds functionality to the main scanning screen. The user can now swipe through the candidates. The scanning cards now display the thumbnails, 3 pinned annotations and the photometry plot. The pinned annotations cannot be changed for now but they will be in the future. In the view with all annotations, the user can copy an annotation line by just tapping it.

The actions button at the bottom are not functional yet, except for the "next" button. This part probably needs more work though as "next", "save" and "discard" are the only actions one can currently perform in the scanning screen. We will have to make a richer toolbar at the bottom with options to at least exit the scanning session or change the options.

For the swiping behavior, I have tried Swiper.js at first, as it is the solution recommended by Ionic. But I found that its performances were slow. So I switched to Embla which is supposed to be more lightweight.

Routing has also been reviewed and is now contained exclusively in the App.jsx component. Finally, loading indicators have been added to replace the `<div>Loading...</div>` that we have everywhere in the application.

The main scanning screen looks like the following:

---

* Use `Suspense` to wait for data in main.jsx, App.jsx, ScanningOptionsScreen.jsx, SourceListScreen.jsx and MainScanningScreen.jsx
* Make `useSkipOnboarding` return user in App.jsx
* New CandidateScanner.jsx component
* Change `history.push` into `history.replace` in CheckQRCodeScreen.jsx and OnboardingLower.jsx
* New `CLEAR_AUTH` config variable to remove persistent authentication
* Replace `useQuery` by `useSuspenseQuery` everywhere we want to wait for data using `Suspense`
* Preload logo image in index.html
* Put all routing in App.jsx
* Change scanning routes from "/app/scanning" to just "/scanning", allowing the tab bar to disappear
* Remove MainScreen.jsx component
* New ScanningHome.jsx component
* Add candidate name to CandidateScanner.jsx
* Add action buttons at the bottom of the scanning screen
* Remove "See more" button from the scanning screen
* Add border to the thumbnail image
* Change background color
* Make Thumbnail.jsx component take only `candidate` and `type` as props
* Add `src` and `setSrc` states to Thumbnail.jsx component
* New PinnedAnnotations.jsx component to display the annotations the user chose to pin
* Replace CandidateAnnotations with PinnedAnnotations.jsx in CandidateScanner.jsx
* New CandidateAnnotationsViewer.jsx component to contain the contents of the annotations modal
* Add `@capacitor/clipboard` plugin to enable copy of annotations values
* New CandidatePhotometryChart.jsx component
* New photometry.json mock file
* New PinnedAnnotationsSkeleton.jsx component
* New ScanningCard.jsx component
* New ScanningCardSkeleton.jsx component
* New ThumbnailSkeleton.jsx component
* Move url params parsing in `useSearchCandidates` hook
* Install `vega-embed` and copy code from the web version to integrate the photometry plot
* Change hook order in CandidateScanner.jsx
* Add skeleton components to be displayed while the data is loading
* Remove suspense from `useSearchCandidates`
* Remove state from `useQueryParams`
* New `fetchSourcePhotometry` function
* New `useSourcePhotometry` hook to fetch photometry data using `fetchSourcePhotometry`
* New requests.js file with new `fetchConfig` function to fetch the config from the SkyPortal instance
* Rename `useSkipOnboarding` hook into `useAppStart`
* Add `bandpassesColors` parameter to `vegaPlotSpec` function
* Rename `vegaPlotSpec` into `getVegaPlotSpec`
* Remove `PREFERENCES` constant and only use `QUERY_KEYS`
* New `fetchConfigAndSetPreference` helper function in hooks.js
* New `useBandpassesColors` hook

### CODE REVIEW

**Comment by Theodlz** [comment]
Hi @dj-256. Just gave it a go and looked at a portion of the code (still going through it but as usual, the code quality is good!).

Few things I noticed:
- Could reduce a little bit the space between the 2 rows of cutouts.
- when clicking "show all", the window opens a little bit and the user has to scroll again to make it tall enough to use it. Idk if this is intentional, but it made it a little harder to use, cause you essentially have to click+swipe up everytime and not just click before one can start scrolling.
- It says there are 50 candidates, but there are 1000 candidates actually. The API call grabs 50 of them and returns the `totalMatches` that indicated the full number for the client to implement pagination. In this PR or the next, you'll want to show that number in the top right, and implement pagination. Also we implement caching so you could just fetch 5, and then next time you call the API provide the queryID which will help return the results quicker. When I played around with developing something like this in SWIFT, using caching I could prefetch the next screens as the user scrolls which made it looks like you could scroll without waiting, which was very nice. You could consider something like that at some point, but yeah even just basic pagination is needed for scanning to work.
- I didn't click it to not save something by accident, but can you remind me the behavior of the green "validate/check" button? Was that to save as a source? If so, do keep in mind that folks often scan for `N` groups but only save to a subset of that. Though we might have discussed this already in which case you can ignore this comment.
- Unrelated to this PR but we would really benefit from a 4th menu where one can see his profile (maybe longer term), but more immediately to log out. Otherwise, can't easily switch between instances.

**Comment by dj-256** [comment]
I fixed your two first points in my last two commits. I opened issue #33 and #34 for the other points. Point 4 will require me to do some thinking back in the scanning options page too. I will make a proposition using the lofi prototype

**Comment by Theodlz** [comment]
> I fixed your two first points in my last two commits. I opened issue #33 and #34 for the other points. Point 4 will require me to do some thinking back in the scanning options page too. I will make a proposition using the lofi prototype

Sounds good. Is this ready for me to review again? If so, please just tag me for review when things are ready.

**Comment by dj-256** [comment]
@Theodlz yes this is ready for review

**Review by Theodlz — APPROVED** [review]
LGTM. UI/UX experience wise this is very nice.

However, the pagination should really get fixed in PR soon. Whether or not you put effort into how you load the data is another problem, and you shouldn't need to do more much than use the `totalMatches` from the response correctly + add another API call when reaching the end of the page. This needs to be fixed soon if we want the scanning page to be usable. Even if you don't have the pagination just yet, displaying the `totalMatches` count and not just `50` in the top right would be nice to avoid confusion.

Honestly you are getting close to a usable scanning page (at least for very simple things. Until we have a way to see more info about a source and some more dataproducts, can't really do too much), and this is the main blocker right now.

**Pull request merged**
