### PR TITLE
#28 Scanning profiles and refactor `userInfo` and `userProfile`

### PR DESCRIPTION
**Pull request by dj-256**
The "Candidates" tab home screen has been replaced by a scanning profile selection screen. This screen has 3 profiles displayed and offers the possibility to directly scan using the default profile of the user or to scan without a profile via buttons at the bottom of the screen.

The "See all" button at the top navigates to a new scanning profile list page where the user can select any profile to scan with and in the next evolutions, we could allow them to also edit and delete profiles from this screen.

I also used the Context API to share `userInfo` across the whole app to prevent constant calls to `getPreferences`. Some parts of the code have also been refactored and cleaned up as well.

---

* New `ScanningProfile` type
* New `UserPreferences` type
* Rename `User` type to `UserProfile` type
* Rename `checkTokenAndFetchUser` function to `fetchUserProfile`
* New context.js file to hold React contexts
* Pass `userInfo` into context rather than fetching it from the preferences every time
* Refactor hooks and request to only take `userInfo` as a parameter rather than having `instanceUrl` and `token` every time
* Remove brackets from `setPreferences` and `getPreferences`
* Do not store `userProfile` anymore, only `userInfo`
* Refactor `useAppStart` to return both `userProfile` and `userInfo`
* New ScanningProfiles.jsx component
* Load profile in ScanningOptionsForm.jsx from the url query parameters
* New `getStartDate` and `getFiltering` functions in scanningLib.js to extract form values from a scanning profile
* Add scanning profiles to user.json mock
* Remove overscroll in places it did not make sense
* New route "/scanning/new-profile" for the profile creation screen
* New ControlledInput.jsx component
* Move `computeSavedStatus` function to scanningLib.js
* Extract new `getDefaultValues` function in scanningLib.js
* New ScanningNewProfileScreen.jsx component
* Wrap form lists, headers and error containers into `div`s with the class `form-section`
* Take list headers out of the list in forms
* New ScanningProfileCreator.jsx component
* New `createNewProfile` function in scanningRequests.js
* New ProfileListItem.jsx component
* New RecentProfiles.jsx component with the original contents from ScanningProfiles.jsx
* Fix toggle in ScanningOptionsProgram.jsx

### CODE REVIEW

**Comment by Theodlz** [comment]
@dj-256 quick comment based on your screenshot: I feel like the 'default' test is not super obvious. Any idea of how to make that a little more obvious?

I think it lacks visual feedback that this one is pre-selected if you see what I mean, it still feels that I should click it.

**Comment by dj-256** [comment]
Ok I can make it stand out more by putting on top and changing the color maybe. That being said, clicking the default profile on the list and clicking the "Scan with default" button have the exact same behavior

**Comment by Theodlz** [comment]
I'll run the code today and let you know how it goes

**Comment by dj-256** [comment]
@Theodlz I've updated the UI like so

**Pull request merged**
