### PR TITLE
24 Implement scanning option page

### PR DESCRIPTION
**Pull request by dj-256**
This PR adds functionality and changes the layout of the scanning options page. It breaks down the ScanningOptionsScreen into a lot of smaller components.
The form now looks like the following:

Here, the user has one program selected and one junk group. As he has only one junk group selected, the discard button will automatically add the current source to this group. If they select more than one group, they get to choose the discarding behavior and if they choose the first option, a select will be displayed to pick which group to discard to.

All the form values are passed to the main scanning page to create the request and start the scanning session.

---
* Create sections and add inline selects
  * Change `<section>` tags into `<fieldset>` tags and add a legend for each one
  * Use include/exclude any/all formulation
  * Restyle `ion-select`s to display them inline
  * New `fetchGroups` function to query groups
  * New `useUserAccessibleGroups` hook to get user accessible groups
  * Move global `ion-select` css to OnboardingLower.scss
* Add modal to select multiple groups
  * Copied code from https://ionicframework.com/docs/api/select#typeahead-component to display multiple selection modal
  * New AppTypeAhead.jsx component
  * Display selected groups as `<ion-chip>`s int the form
* Refactor directory structure
* Enforce module structure by creating a new `common/` directory and putting all the `util/` files in it along with AppTypeAhead.jsx component
* Rename AppTypeAhead.jsx into MultiSearchSelect
* Break form into multiple components
  * New ScanningOptionsForm.jsx component
  * New ScanningOptionsDate.jsx component
  * New ScanningOptionsProgram.jsx component
  * New ScanningOptionsDiscarding.jsx component
  * New CandidateFiltering.jsx component
  * New ControlledMultiSearchSelect.jsx component
  * Use moment-timezone to normalize and compare dates
  * Add validation to form
  * Wrap candidate filtering in a React Hook Form `Controller`
  * Change the layout of the program selection and candidate filtering
* Create `scanningOptions` and `scanningSession` submodules in `scanning` directory
* `ErrorMessage` and `ControlledDateTime`
  * New ErrorMessage.jsx component
  * New ControlledDateTime.jsx component
  * Use controlled `ion-datetime` elements in form
* Make form submit work
  * ScanningOptionsForm.jsx: New `computeSavedStatus` to compute the saved status string from the form inputs
  * ScanningOptionsForm.jsx: Parse inputs in `onSubmit` and navigate to the main scanning screen
  * MainScanningScreen.jsx: Parse options from url parameters and pass them to `useSearchCandidates`
  * scanning.js: change `searchCandidates` function to accept mor parameters
  * ScanningOptionsProgram.jsx: Use `watch` to get the `selectedGroups`
* Remove `selectedGroup` state from ScanningOptionsForm.jsx component and use React Hook Form values instead
* Remove ScanningHomeScreen.jsx component
* Change discarding section in form
  * New ControlledRadioGroup.jsx component
  * Allow multiple junk group selection
  * Add discard button behavior options
  * Remove `junkGroup` state from the form
* Create `navigateWithParams` helper function
* Add single junk group select
  * Rename `TypeAhead` directory into `MultiSearchSelect`
  * Add `rules` and `title` parameters to ControlledMultiSearchSelect.jsx component
  * Add select element to ScanningOptionsDiscarding.jsx to select the junk group to discard to when the user selects "Discard to a specific junk group"

### CODE REVIEW

**Comment by Theodlz** [comment]
I get this error @dj-256:

```bash
[vite] 10:02:49 AM [vite] Internal server error: Failed to resolve import "@capacitor/preferences" from "src/util/preferences.js". Does the file exist?
[vite]   Plugin: vite:import-analysis
[vite]   File: /Users/theodlz/projects/students/skyportal-mobile-ionic/src/util/preferences.js:1:30
[vite]   1  |  import { Preferences } from "@capacitor/preferences";
```

**Review by Theodlz — COMMENTED** [review]
UI looks great! Very easy to use it and search for groups, I'm happy with the screen.

One thing to note is - though could be addressed in another PR:
- after clicking search/scan and getting results (or no results), swiping left/right on my device to go back does not work properly and sends me back to the "connected successfully" screen, where it is now stuck.
- I would rename "discarding" to "junk". Both make sense but the later is what your userbase will look for and by design are the groups to which things are discarded anyway.
- it allows me to click "scan" even if I didn't select anything, which should probably show a little error msg, and you could have the button deactivated when nothing is selected yet.
- would be good to have persistence of the options selected or use the concept of scanning profiles like we have in the web app, but again that's probably for another PR of course.

**Comment by dj-256** [comment]
> UI looks great! Very easy to use it and search for groups, I'm happy with the screen.
> 
> One thing to note is - though could be addressed in another PR:
> 
> * after clicking search/scan and getting results (or no results), swiping left/right on my device to go back does not work properly and sends me back to the "connected successfully" screen, where it is now stuck.
> * I would rename "discarding" to "junk". Both make sense but the later is what your userbase will look for and by design are the groups to which things are discarded anyway.
> * it allows me to click "scan" even if I didn't select anything, which should probably show a little error msg, and you could have the button deactivated when nothing is selected yet.
> * would be good to have persistence of the options selected or use the concept of scanning profiles like we have in the web app, but again that's probably for another PR of course.

I handled point 2 and 3 and opened issues #27 and #28 for points 1 and 4

**Comment by Theodlz** [comment]
Awesome @dj-256. Then feel free to merge once this is ready.

**Pull request merged**
